### ISSUE TITLE
Mario's dissolve effect when using vanish cap and teleporting missing

### ISSUE THREAD

**Issue by Reonu** [sm64pc/sm64ex#155]
**Describe the bug**
When Mario uses the vanish cap or teleports, there's supposed to be a super cool looking dissolve effect. Instead, in the PC version, he becomes trasparent.

**To Reproduce**
1. Use the vanish cap or teleport.

**Expected behavior**
The dissolve effect appears.

**Screenshots**
Original N64 effect:
![imagen](https://user-images.githubusercontent.com/15913880/82145088-3e5f8e00-9840-11ea-9f73-cf63edc5a327.png)
![imagen](https://user-images.githubusercontent.com/15913880/82145117-7535a400-9840-11ea-8fd4-36c447dec773.png)

In the PC version:
![imagen](https://user-images.githubusercontent.com/15913880/82145101-5b945c80-9840-11ea-8ef7-e0bc4e53122d.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 64 bits

**Additional context**
This also happens in emulator when using low quality graphics plugins such as Jabo. The screenshot of the effect rendering properly is using Glide.

**Comment by BailShamber** [comment]
It might get implemented soon.
https://github.com/Emill/n64-fast3d-engine/pull/6

**Comment by Leon422** [comment]
Awesome! I have seen concerns that it might be too performance demaning for very low end devices such as the Raspberry Pi so allow me to suggest before it gets implemented that I think it should be an option that the user can toggle in the display Options, if possible, since this single effect will probably be more demanding that the entire rest of the game lol

**Comment by fgsfdsfgs** [comment]
Closing because noise has been in for a while.
