### ISSUE TITLE
Cross compiling to the psp

### ISSUE THREAD

**Issue by Titaniumtown** [sm64pc/sm64ex#182]
Is it possible to cross-compile sm64pc for my psp? (yes I still have one, and yes I use it pretty much daily) I have all the tools installed on my pc, including psp-sdl, psp-opengl, along with psp-gcc.

Thanks!

**Comment by fgsfdsfgs** [comment]
You will have to write a native PSP replacement for `gfx_opengl.c`. If you do, then probably?

**Comment by IvanDSM** [comment]
I took a look at pspgl and it says it only supports base OpenGL but doesn't say what version. I suppose you could try compiling it. That is, if psp-sdl is SDL2. If it's SDL1 then you'll need to change some things around. I think that ultimately, even if pspgl works, it would be better to write a replacement as suggested by fgsfdsfgs, since it's a very old and hacky library.

**Comment by fgsfdsfgs** [comment]
You could try using the new legacy GL backend with pspgl, but that requires `GL_ARB_multitexture` and `GL_ARB_texture_env_combine`, which are part of GL1.3 (and may be implemented on cards that support 1.2), and I don't know whether pspgl implements that.

**Comment by vrmiguel** [comment]
Closing question due to inactivity.
