### ISSUE TITLE
[Nightly] Vanish Cap Switch Course crash

### ISSUE THREAD

**Issue by Busybuss** [sm64pc/sm64ex#437]
**Describe the bug**
Trying to enter the Vanish cap switch course causes the game to crash

**To Reproduce**
1. Build normally
2. Start game with a save that does not have the vanish cap unlocked and can access he basement
3. Try to enter Vanish Cap Switch Course within the mushroom castle moat
4. The game crashes

**Expected behavior**
The Vanish Cap Switch Course loads in as expected

**Desktop (please complete the following information):**
 - OS: [Windows 10]

**Comment by fgsfdsfgs** [comment]
What build flags, mods?

**Comment by Busybuss** [comment]
mod 60fps patch
build flags 
BETTERCAMERA
TEXTURE_FIX

**Comment by Busybuss** [comment]
**It seems that enabling free camera before entering the course is what causing the bug.

**Comment by Busybuss** [comment]
Even if you've activated the switch, if you enter the course with free camera enabled the game will crash.

**Comment by porcino** [comment]
The crash was introduced in this commit 75bed240faf6997f3e3683303ab325b7fd164965
To fix this crash, change in src/engine/surface_collision.c 
```
// increase collision checking precision (normally 1)
    f32 precision = 3;
```
to 
```
// increase collision checking precision (normally 1)
    f32 precision = 1;
```

**Comment by djoslin0** [comment]
Since this regression was introduced due to my change, I was really curious what could cause it. The crash doesn't happen in sm64ex-coop, but I'm still not sure why yet.

The segfault is triggered in `geo_process_node_and_siblings()` due to `firstNode->parent` being set to a garbage value.
`firstNode` is obtained by grabbing `node->children` in `geo_try_process_children()`. There, the `node` isn't corrupted.
It turns out `node` is grabbed from an object in `geo_process_object()`, specifically it's a `bhvCheckerboardElevatorGroup`.
Now.. why a change in camera code is causing the checkerboard elevator group's node graph to be corrupted is anyone's guess.

I can confirm that setting `precision` to 1 as the above comment suggests does fix the crash. However, it re-introduces the flaw with bettercam where the collision checks are in-precise and therefore the camera goes through walls again. I'll keep digging

**Comment by djoslin0** [comment]
Hours of debugging later: so it looks like the allocator is rewriting memory that is currently in use.
The elevator group uses a node set by a spawnInfo, and everything is fine up until `add_surface_to_cell()` comes along and makes a call to `alloc_surface_node()` which rewrites what was `GraphNode` data with `Surface` data...

You can see this happen yourself by compiling with `DEBUG=1` and running gdb with this command:
`watch gLoadedGraphNodes[55].children`
This watches the elevator group's model's `GraphNode` for the change that corrupts the memory.

Note: you have to hit a breakpoint before the watchpoint is allowed to be hit for some reason. I typically set one like this:
`b init_level`
And when it's hit just type `c`.

I'm at a loss for why this happens when the precision is set higher since that code isn't called between the start of level loading and when `load_static_surfaces()` is called (which is where the corruption happens).

It seems like reducing `precision` to 1 is the best option for now unless anyone else is willing to dig through gdb.

**Comment by djoslin0** [comment]
I couldn't help myself, I dug in again today.
So here's some background: `bhvCheckerboardElevatorGroup` is the invisible parent object that defines where the two platforms will rotate around. It has a model, but it's never rendered in game. The entity only exists for a few frames before being removed from the scene.

Here's the theory: Since it is only valid for a few frames, I believe the model gets deallocated after removal. Since changing the camera precision makes the camera end up in a slightly different spot, it could be trying to render the object when `precision` is set to 3 but not to 1.

Here's the solution: Adding `cur_obj_hide()` to the start of `bhv_checkerboard_elevator_group_init()` prevents the crash.

**Comment by djoslin0** [comment]
Opened pull request https://github.com/sm64pc/sm64ex/pull/439
